server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Fichiers statiques du frontend
    location / {
        try_files $uri $uri/ =404;
    }

    # Reverse-proxy vers le microservice Livres
    location /api/books {
        proxy_pass http://books-service:3001/api/books;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Reverse-proxy vers le microservice Utilisateurs
    location /api/users {
        proxy_pass http://users-service:3002/api/users;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Reverse-proxy vers le microservice Emprunts
    location /api/loans {
        proxy_pass http://loans-service:3003/api/loans;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
